name: AzD Extension

on:
  push:
    branches:
    - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
    - master

jobs:
  vscode-extension:
    name: AzD Extension
    runs-on: ubuntu-latest 

    steps:
    
    - uses: actions/checkout@v1

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x 

    - name: NPM Install & Compile
      env: # Set the secret as an input
        AZD_TOKEN: ${{ secrets.AZD_TOKEN }}
      run: | 
        npm install
        npm run build
        npm install -g tfx-cli
        #tfx login  --service-url https://marketplace.visualstudio.com --token $AZD_TOKEN

    - name: Create [dev] Extension
      if: github.ref == 'refs/heads/develop'
      run: | 
        tfx extension create
    
    - name: Create [prd] Extension
      if: github.ref == 'refs/heads/master'
      run: | 
        tfx extension create --extension-id sprint-goal --override '{ \"name\": \"Sprint Goal\" }'

    - name: Publish Extension
      run: | 
        tfx extension publish --service-url https://marketplace.visualstudio.com --token $AZD_TOKEN