name: AzD Extension

on: [ push, pull_request]

jobs:
  vscode-extension:
    name: AzD Extension
    runs-on: ubuntu-latest 

    steps:
    
    - uses: actions/checkout@v1

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x 

    - name: NPM Install & Compile
      run: | 
        npm install
        npm run build
        tfx extension create 